require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.lualine"
-- require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
-- require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.transparent"
require "user.dap"
-- require "user.trouble"
require "user.lsp-router"
require "user.harpoon"
require "user.todo"
require "user.numb"
require "user.gps"
